apiVersion: v1
kind: Service
metadata:
  name: __IMAGE_NAME__
  namespace: __NAMESPACE__
  labels:
    app: __IMAGE_NAME__
    service: __IMAGE_NAME__
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    service: __IMAGE_NAME__
