on:
  workflow_call:
    inputs:
      CONTAINER_NAME:
        required: true
        type: string
      ROUTE_BASE_INGRESS:
        required: false
        type: string
        default: 'false'       
      DOCKER_PATH:
        required: false
        type: string
        default: "./Dockerfile"
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      PACKAGE_READ:
        required: true

env:
  AZURE_CONTAINER_REGISTRY: "warshipregistry"
  CLUSTER_NAME: "aks"

jobs:
  BuildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: "CombatWarships"
    steps:
      # Checks out the repository 
      - uses: actions/checkout@v3

  #    - name: Prep Package Source
  #      run: dotnet nuget add source --username CombatWarships --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/CombatWarships/index.json"

      - name: Update DOCKER variables 
        uses: cschleiden/replace-tokens@v1.2
        with:
          files: '["${{inputs.DOCKER_PATH}}"]'
          tokenPrefix: __
          tokenSuffix: __
        env:
          USERNAME: JustinKScott
          TOKEN: ${{ secrets.PACKAGE_READ }}

      # Logs in with your Azure credentials
      - name: Azure login 
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az acr build -f ${{inputs.DOCKER_PATH}} --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ inputs.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .

  DevelopmentDeploy: 
    permissions:
      actions: read
      contents: read
      id-token: write  
    needs: BuildImage
    uses: CombatWarships/DevOps/.github/workflows/Deploy.yml@main
    with:
      ENVIRONMENT: Development
      CONTAINER_NAME: ${{ inputs.CONTAINER_NAME }}
      ROUTE_BASE_INGRESS: ${{ inputs.ROUTE_BASE_INGRESS }}
    secrets: 
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}  
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}

  ProductionDeploy: 
    permissions:
      actions: read
      contents: read
      id-token: write  
    needs: DevelopmentDeploy
    uses: CombatWarships/DevOps/.github/workflows/Deploy.yml@main
    with:
      ENVIRONMENT: Production
      CONTAINER_NAME: ${{ inputs.CONTAINER_NAME }}
      ROUTE_BASE_INGRESS: ${{ inputs.ROUTE_BASE_INGRESS }}
    secrets: 
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}  
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
