on:
  workflow_call:
    inputs:
      CONTAINER_NAME:
        required: true
        type: string
    secrets:
      DBConnection:
        required: true
      APP_INSIGHTS:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

env:
  AZURE_CONTAINER_REGISTRY: "warshipregistry"
  CONTAINER_NAME: ${{ inputs.CONTAINER_NAME }}
  DOCKER_PATH: "./Dockerfile"
  APPSETTINGS_PATH: "./appsettings.json"
  CLUSTER_NAME: "aks"

jobs:
  BuildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: "CombatWarships"
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      #substitute production appsettings entries to appsettings json file
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.APPSETTINGS_PATH }}
        env:
          ConnectionStrings.DBConnection: ${{secrets.DBConnection}}
          ConnectionStrings.AppInsights: ${{secrets.APP_INSIGHTS}}
          
      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az acr build -f ${{env.DOCKER_PATH}} --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .

          
